apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctool-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ctool-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ctool-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ctool-api
        image: hiclass.azurecr.io/ctool-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 19081
        resources:
          requests:
            cpu: 1000m
          limits:
            cpu: 1000m
        livenessProbe:
          httpGet:
            path: /
            port: 19081
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 19081
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 3
          timeoutSeconds: 10
      imagePullSecrets:
        - name: acrsecret
---
apiVersion: v1
kind: Service
metadata:
  name: ctool-api
spec:
  # type: LoadBalancer
  type: ClusterIP  # required ingress
  ports:
  - port: 80
    targetPort: 19081
  selector:
    app: ctool-api