apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: springboot-test
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: springboot-test
        image: registrycontainerforebayjp.azurecr.io/springboot:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 19082
        resources:
          requests:
            cpu: 1000m
          limits:
            cpu: 1000m
        livenessProbe:
          httpGet:
            path: /
            port: 19082
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 19082
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 3
          timeoutSeconds: 10
      # imagePullSecrets:
      #   - name: acrsecret
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-test
spec:
  # type: LoadBalancer
  type: ClusterIP  # required ingress
  ports:
  - port: 80
    targetPort: 19082
  selector:
    app: springboot-test
